void animation()
	{
		//usleep(20000);
		cout << "." << endl;
        usleep(20000);
        system("clear");
        usleep(20000);
        system("clear");
        cout << ".." << endl;
        usleep(20000);
        system("clear");
        cout << "..." << endl;
        usleep(20000);
        system("clear");
        cout << "...." << endl;
        usleep(20000);
        system("clear");
        cout << "....." << endl;
        usleep(20000);
        system("clear");
        cout << "......" << endl;
        usleep(20000);
        system("clear");
        cout << "......." << endl;
        usleep(20000);
        system("clear");
        cout << "........" << endl;
        usleep(20000);
        system("clear");
        cout << "........." << endl;
        usleep(20000);
        system("clear");
        cout << ".........." << endl;
        usleep(20000);
        system("clear");
        cout << "..........." << endl;
        usleep(20000);
        system("clear");
        cout << "............" << endl;
        usleep(20000);
        system("clear");
        cout << "............." << endl;
        usleep(20000);
        system("clear");
        cout << ".............." << endl;
        usleep(20000);
        system("clear");
        cout << "..............." << endl;
        usleep(20000);
        system("clear");
        cout << "................" << endl;
        usleep(20000);
        system("clear");
        cout << "................." << endl;
        usleep(20000);
        system("clear");
        cout << ".................." << endl;
        usleep(20000);
        system("clear");
        cout << "..................." << endl;
        usleep(20000);
        system("clear");
        cout << "...................." << endl;
        usleep(20000);
        system("clear");
        cout << "....................." << endl;
        usleep(20000);
        system("clear");
        cout << "......................" << endl;
        usleep(20000);
        system("clear");
        cout << "......................." << endl;
        usleep(20000);
        system("clear");
        cout << "........................" << endl;
        usleep(20000);
        system("clear");
        cout << "........................." << endl;
        usleep(20000);
        system("clear");
        cout << ".........................." << endl;
        usleep(20000);
        system("clear");
        cout << "..........................." << endl;
        usleep(20000);
        system("clear");
        cout << "............................" << endl;
        usleep(20000);
        system("clear");
        cout << "............................." << endl;
        usleep(20000);
        system("clear");
        cout << ".............................." << endl;
        usleep(20000);
        system("clear");
        cout << "..............................." << endl;
        usleep(20000);
        system("clear");
        cout << "................................" << endl;
        usleep(20000);
        system("clear");
        cout << "................................." << endl;
        usleep(20000);
        system("clear");
        cout << ".................................." << endl;
        usleep(20000);
        system("clear");
        cout << "..................................." << endl;
        usleep(20000);
        system("clear");
        cout << "...................................." << endl;
        usleep(20000);
        system("clear");
        cout << "....................................." << endl;
        usleep(20000);
        system("clear");
        cout << "......................................" << endl;
        usleep(20000);
        system("clear");
        cout << "......................................." << endl;
        usleep(20000);
        system("clear");
        cout << "........................................" << endl;
        usleep(20000);
        system("clear");
        cout << "........................................." << endl;
        usleep(20000);
        system("clear");
        cout << ".........................................." << endl;
        usleep(20000);
        system("clear");
        cout << "..........................................." << endl;
        usleep(20000);
        system("clear");
        cout << "............................................" << endl;
        usleep(20000);
        system("clear");
        cout << "............................................." << endl;
        usleep(20000);
        system("clear");
        cout << ".............................................." << endl;
        usleep(20000);
        system("clear");
        cout << "..............................................." << endl;
        usleep(20000);
        system("clear");
        cout << "................................................" << endl;
        usleep(20000);
        system("clear");
        cout << "................................................." << endl;
        usleep(20000);
        system("clear");
        cout << ".................................................." << endl;
        usleep(20000);
        system("clear");
        cout << "..................................................." << endl;
        usleep(20000);
        system("clear");
        cout << "...................................................." << endl;
        usleep(20000);
        system("clear");
        cout << "....................................................." << endl;
        usleep(20000);
        system("clear");
        cout << "......................................................" << endl;
        usleep(20000);
        system("clear");
        cout << "......................................................." << endl;
        usleep(20000);
        system("clear");
        cout << "........................................................" << endl;
        usleep(20000);
        system("clear");
        cout << "........................................................." << endl;
        usleep(20000);
        system("clear");
        cout << ".........................................................." << endl;
        usleep(20000);
        system("clear");
        cout << "..........................................................." << endl;
        usleep(20000);
        system("clear");
        cout<<endl;

		cout << "............................................................" << endl;
		usleep(20000);
        system("clear");
		cout << "..........................................................." << endl;
		usleep(20000);
        system("clear");
		cout << ".........................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "........................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "........................................................" << endl;
		usleep(20000);
        system("clear");
		cout << "......................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "......................................................" << endl;
		usleep(20000);
        system("clear");
		cout << "....................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "...................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "..................................................." << endl;
		usleep(20000);
        system("clear");
		cout << ".................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "................................................." << endl;
		usleep(20000);
        system("clear");
		cout << "................................................" << endl;
		usleep(20000);
        system("clear");
		cout << "..............................................." << endl;
		usleep(20000);
        system("clear");
		cout << ".............................................." << endl;
		usleep(20000);
        system("clear");
		cout << "............................................." << endl;
		usleep(20000);
        system("clear");
		cout << "............................................" << endl;
		usleep(20000);
        system("clear");
		cout << "..........................................." << endl;
		usleep(20000);
        system("clear");
		cout << ".........................................." << endl;
		usleep(20000);
        system("clear");
		cout << "........................................." << endl;
		usleep(20000);
        system("clear");
		cout << "........................................" << endl;
		usleep(20000);
        system("clear");
		cout << "......................................." << endl;
		usleep(20000);
        system("clear");
		cout << "......................................" << endl;
		usleep(20000);
        system("clear");
		cout << "....................................." << endl;
		usleep(20000);
        system("clear");
		cout << "...................................." << endl;
		usleep(20000);
        system("clear");
		cout << "..................................." << endl;
		usleep(20000);
        system("clear");
		cout << ".................................." << endl;
		usleep(20000);
        system("clear");
		cout << "................................." << endl;
		usleep(20000);
        system("clear");
		cout << "................................" << endl;
		usleep(20000);
        system("clear");
		cout << "..............................." << endl;
		usleep(20000);
        system("clear");
		cout << ".............................." << endl;
		usleep(20000);
        system("clear");
		cout << "............................." << endl;
		usleep(20000);
        system("clear");
		cout << "............................" << endl;
		usleep(20000);
        system("clear");
		cout << "..........................." << endl;
		usleep(20000);
        system("clear");
		cout << ".........................." << endl;
		usleep(20000);
        system("clear");
		cout << "........................." << endl;
		usleep(20000);
        system("clear");
		cout << "........................" << endl;
		usleep(20000);
        system("clear");
		cout << "......................." << endl;
		usleep(20000);
        system("clear");
		cout << "......................" << endl;
		usleep(20000);
        system("clear");
		cout << "....................." << endl;
		usleep(20000);
        system("clear");
		cout << "...................." << endl;
		usleep(20000);
        system("clear");
		cout << "..................." << endl;
		usleep(20000);
        system("clear");
		cout << ".................." << endl;
		usleep(20000);
        system("clear");
		cout << "................." << endl;
		usleep(20000);
        system("clear");
		cout << "................" << endl;
		usleep(20000);
        system("clear");
		cout << "..............." << endl;
		usleep(20000);
        system("clear");
		cout << ".............." << endl;
		usleep(20000);
        system("clear");
		cout << "............." << endl;
		usleep(20000);
        system("clear");
		cout << "............" << endl;
		usleep(20000);
        system("clear");
		cout << "..........." << endl;
		usleep(20000);
        system("clear");
		cout << ".........." << endl;
		usleep(20000);
        system("clear");
		cout << "........." << endl;
		usleep(20000);
        system("clear");
		cout << "........" << endl;
		usleep(20000);
        system("clear");
		cout << "......." << endl;
		usleep(20000);
        system("clear");
		cout << "......" << endl;
		usleep(20000);
        system("clear");
		cout << "....." << endl;
		usleep(20000);
        system("clear");
		cout << "...." << endl;
		usleep(20000);
        system("clear");
		cout << "..." << endl;
		usleep(20000);
        system("clear");
		cout << ".." << endl;
		usleep(20000);
        system("clear");
		cout << "." << endl;
		usleep(20000);
        system("clear");

	
			
	}
